server:
  port: 8080

spring:
  application:
    name: mcp-streaming-service
  
  # Jackson configuration for JSON serialization
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Logging configuration
logging:
  level:
    com.example.mcpstreaming: INFO
    reactor.netty.http.server: INFO
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Custom application properties
app:
  user:
    # Home directory path - defaults to system property user.home
    # Can be overridden for testing or different environments
    # home: /Users/chris
    
mcp:
  streaming:
    # Maximum concurrent streams per client
    max-concurrent-streams: 10
    # Default timeout for operations
    default-timeout-seconds: 300
    # Maximum file size for operations (in bytes)
    max-file-size-bytes: 10485760  # 10MB
    # Security settings
    security:
      # Enable command validation
      validate-commands: true
      # Allow dangerous commands (for testing only)
      allow-dangerous-commands: false